
# POST http://localhost:3333/driver/register/ HTTP/1.1
# Content-Type: application/json

# {
#     "driver_Id": 123456789,
#     "hauseNumber": "3",
#     "language": "portuge",
#     "startPrice": 25.00,
#     "trips": 122,
#     "doHelp": true,
#     "driverAvatarUrl": "urlddjddd",
#     "carImgUrl1": "urlddjddd",
#     "carImgUrl2": "urlddjddd",
#     "carImgUrl3": "urlddjddd",
#     "carImgUrl4": "urlddjddd",
#     "carImgUrl5": "urlddjddd",
#     "docUrl1": "urlddjddd",
#     "docUrl2": "urlddjddd",
#     "docUrl3": "urlddjddd",
#     "docUrl4": "urlddjddd"
    
# }


POST http://localhost:3333/auth/login/ HTTP/1.1
Content-Type: application/json

{
   "email":"mauro.developer.br@gmail.com",
   "password":"1234567"
}
